//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatchPhotoEntities : DbContext
    {
        public MatchPhotoEntities()
            : base("name=MatchPhotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PHOTO_COMMENT> PHOTO_COMMENT { get; set; }
        public virtual DbSet<PHOTO_LOVED> PHOTO_LOVED { get; set; }
        public virtual DbSet<PHOTO_MATCH> PHOTO_MATCH { get; set; }
        public virtual DbSet<PHOTO_PICTURE> PHOTO_PICTURE { get; set; }
        public virtual DbSet<PHOTO_USER> PHOTO_USER { get; set; }
        public virtual DbSet<PHOTO_WECHAT_USER> PHOTO_WECHAT_USER { get; set; }
    }
}
