//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHOTO_USER
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public System.DateTime Ctime { get; set; }
        public System.DateTime Mtime { get; set; }
        public string Createdby { get; set; }
        public string Modifiedby { get; set; }
    }
}
